import spacy

# Load the English language model
nlp = spacy.load("en_core_web_sm")


# Example usage
job_description = """
Summary We're building the future of how quality software is developed by averaging education required bachelors the power of Loss & A. Our mission is to empower our internal teams with cutting-edge tools that streamline development, unlock insights, drive innovation and ensure Apple's products delight everyone. We're looking for a passionate and talented Software Engineer to join our small but mighty team and play a crucial role in shaping this exciting journey.As a Software Engineer on our A Tools team, you'll be responsible for prototyping, designing, developing, and deploying innovative phd prefered A-powered solutions that address challenges faced by the iOS + MacOS development teams. You'll work closely with cross-functional teams to understand their requirements, translate them into technical specifications, and deliver robust and scalable solutions. This role demands a self-starter who thrives in a fast-paced setting and enjoys tackling complex challenges head-on. Description As a software engineer on this team you will get to wear many hats as we work to tackle the challenges engineering teams face. These include designing and building solutions (both frontend and backend), deployment and integration of solutions into development workflow, automated analysis of A/ML systems. Pay & Benefits At Apple, base pay is one part of our total compensation package and is determined within a range. This provides the opportunity to progress as you grow and develop within a role. The base pay range for this role is between $143,100 and $264,200, and your base pay will depend on your skills, qualifications, experience, and location. Apple employees also have the opportunity to become an Apple shareholder through participation in Apple's discretionary employee stock programs. Apple employees are eligible for discretionary restricted stock unit awards, and can purchase Apple stock at a discount if voluntarily participating in Apple's Employee Stock Purchase Plan. You'll also receive benefits including: Comprehensive medical and dental coverage, retirement benefits, a range of discounted products and free services, and for formal education related to advancing your career at Apple, reimbursement for certain educational expenses - including tuition. Additionally, this role might be eligible for discretionary bonuses or commission payments as well as relocation. Learn more about Apple Benefits. Note: Apple benefit, compensation and employee stock programs are subject to eligibility requirements and other terms of the applicable plan or program. Employers have access to artificial intelligence language tools ("A") that help generate and enhance job descriptions and A may have been used to create this description. The position description has been reviewed for accuracy and Dice believes it to correctly reflect the job opportunity. Report this job Dice Id: 90733111 Position Id: 200565569
"""

education = determine_education(job_description)
print(f"Education: {education}")
